source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KFImageCarouselView_Example', :exclusive => true do
  pod "KFImageCarouselView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KFImageCarouselView", :path => "../"

  
end
